---
name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run setup
        uses: ./.github/actions/setup-workspace

      - name: Run tests
        run: |
          just test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run setup
        uses: ./.github/actions/setup-workspace

      - name: Build binary
        run: |
          just tidy
          go mod download all
          CGO_ENABLED=0 GOOS=linux go build -o ./smokesweep main.go

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: smokesweep-binary
          path: smokesweep
