name: Production Release

on:
  push:
    branches:
      - main
    paths:
      - "info.json"

jobs:
  verify:
    name: Verify project state
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run workspace setup
        uses: ./.github/actions/setup-workspace

      - name: Run tests
        run: |
          just test

  release:
    name: Create release
    runs-on: ubuntu-latest
    if: ${{ github.event.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
    needs: verify
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run setup
        uses: ./.github/actions/setup-workspace

      - name: Set version
        id: set-version
        run: |
          export VERSION=$(jq -r .version info.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Release
        uses: jgfranco17/devops/shared-actions/create-release
        with:
          spec-file: info.json
          git-token: ${{ secrets.GITHUB_TOKEN }}
          release-notes-dir: .github/release
